travis:
  secure:
    BINSTAR_TOKEN: hFJSci9lQrN+vJbSIcING+XzVAZ7PKYKPW4bziMEZIx5ESjoa2UEivkQ2jR3O2KNBDEPFeEbquCCvk01Y+YGn1aVo8iLOQyji4K9TVWt1+myStYz5jYSjKN4Sfy86sLgWgVuwj26h85CakdIsQw7m8lu1YrdqLp6sMcr+xX6W9ue1dfffDJJHNiEqcmQ/zN8ciIgqa1c2VK0wdkqZ/Ol16XkQmO+AXbRyqo/u6kmlBgXoZIEAXbRsa5OgpSgciGjMycHgeJ9fEjl4UuRhghod/8AEgb+715MXMjNStvv5IphRHSdGgWBcTKTB6G7051+yU3uHFuuis0DdMuY09Oe28lGovhW1mRo5tzx5BHLZYX8NWQAJEHCT5EoZF0oUBF/26Uhdtic0kSVMWpdp7C3eowUvjXtw+8Rd88mzR45+mPCeCR9VCzLkCnj+Fv0KSNaOrI98Z50bEvBiH3Q2bW7FAY1KYIbM/HGc3lBgz4ggSJSFPYeMZbc8ERNrr+a0zk/8GcmjfeHbFAYCy4Y/aXc2OZnUlti4h2dCMXTmfcJcDSIKR3OZhNCC2Wz5pBgt/dBfTHG9vjlMiyKGZgDC4V4UpzdB19/bMm17OPLYpRQ86l4Sj8Mk7FkHG++o4qpoBEN7vslhRUhLtMag49JEXWYBD6R7IyOvDZFkgBKsyIzyBU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
